### ISSUE TITLE
[S10E05]时间帐单 体验追踪

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/GC4E15gDAMA#1]
## 背景
全新的作业任务, 先完成全新的自省, 再进行回顾总结

## 方案
- 相互监督
- 坚持记录
- 定期回顾
- 持续撰写
- 有任何提案, 回复此 Issue 记录发起讨论

## 进展
找到敌人: 3.27~4.3 各自记录

- [x] `d0` 3.27 构思准备
- [x] `d1` 3.28 开始日记
- [x] `d2` 3.29 ...
- [x] `d3` 3.30 ...
- [x] `d4` 3.31 ...
- [x] `d5` 4.1 ...
- [x] `d6` 4.2 ...
- [x] `d7` 4.3 获得一周样本数据

处决敌人:  4.4~4.9 和合小结

+ [x] `d8 ` 4.4 小结初稿
+ [ ] `d9 ` 4.5 小结稿1
+ [ ] `d10` 4.6 小结稿2
+ [ ] `d11` 4.7 小结稿3
+ [ ] `d12` 4.8 小结稿4
+ [ ] `d13` 4.9 小结稿5
+ [ ] `d14` 4.4 小结稿6

**Comment by ZoomQuiet** [comment]
@GC4WP/zq4s07e15 (有关时间管理最近一次分享)

- 幻灯: http://t.cn/R6asiGe (坑,应该能自行发现如何翻页)
- 录音: http://t.cn/R6ashOy
- 以及 GTD 等相关概念都可以了解一下

**Comment by sallysong007** [comment]
今天上午装了aTime logger 2，时间记录器。
界面简单友好，清晰地列满了大概一天里人们的主要活动选项。如果没有符合自己行动的，还可以在类别里添加。不过，养成开启行动记录的动作我还没有习惯，漏掉了大部分事项，争取利用一周时间形成样本记录……我好像看到了因为浪费时间而对自己的进行的拷问，啊啊啊啊。

**Comment by BrookSongBrookSong** [comment]
＃成员笔记——029 坑3

1. 我觉得少了洗漱的按钮，所以起床后就没再记录了。所以想知道自定义按钮的方法。
2. 上班族，感觉不需要全天纪录，从到家那一刻开始，纪录自己晚间空闲时间的浪费时间情况，比较有价值。
3. 实践了自定义按钮，因为懒的人设，所以我觉得把主要项目设置成按钮追踪即可，其他所有事情全都丢进一个叫做“wasting”的按钮，没错，我就是这样整理电脑桌面的。
4. 我发现浪费的时间3个小时过的飞快，而做项目的时间两个小时就觉得很漫长。

**Comment by ZoomQuiet** [comment]
@BrookSongBrookSong

> 上班族，感觉不需要全天纪录

是也乎,(￣▽￣)
这才是最大的偏见税了...
时间帐单, 首先改进的应该就是每天最大的时间块中的黑洞...
我们当然认为,自己在工作时间是一直稳定努力工作的..

其实, 恰恰相反...

多数网购都在工作时间完成下单的...

**Comment by mammoth2008** [comment]
然也~

大妈+10086

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed

迁移 ed
