### ISSUE TITLE
[gh] 越来越方便的平台

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/GC4E15gDAMA#2]
## 背景
随着佩哥哥的嗯哼, 大家都开始进入 github 协同写作

## 现象
- 不同的入口(手机/桌面/平板/...)
- 不同的习惯
- 不同的性格
- 不同的学习速度
- ....
- 大家享用 github 的速度难以跟上

## 方案

持续的相互参照, 加速 github 使用习惯的传播

当前已知命题的研究作业有:

- [ ] @anxinzhu 026-上海-安心竹 
    + [x] 手机 github 使用手册
    + [ ] MBAir 使用 github 高级姿势
- [ ] @BrookSongBrookSong 029-香港-宋偲瑄
    + [ ] dashboard 进入姿势
- [ ] @expressseven 253-上海-申小七
    + [ ] 移动中 github 使用姿势
- [ ] @sallysong007 193—天津—海岸线
    + [ ] windows 桌面 github 使用姿势
- [ ] ...

参考:

- [[init.]如何进入和合阵地?](https://github.com/GC4WP/S07E15gDAMA/issues/1)
- [[TUV]Github 实效使用方法集锦](https://github.com/GC4WP/S07E15gDAMA/issues/4)
    + [[知情咒] 协同工作工具说明（需成员 chk）](https://github.com/GC4WP/S03E05/issues/5)
    + [S07E15g193: 嗯哼重来](http://www.jianshu.com/p/04b10e675998)
    + [「私塾7.2/36」和合技BC 模式](http://www.jianshu.com/p/ba524d020a06)
    + [「私塾7.1/36」和合技C-C模式](http://www.jianshu.com/p/d90f5df63e18)
    + [小白勿方：github全手机“好中文和合技”使用手册](http://www.jianshu.com/p/63be2a0ced78)
    + [GitHub在文档编辑修改上与Word有什么不同？](http://www.jianshu.com/p/cf4585eabf99)
    + ...

## 进展
~ 大家持续的回复此 Issue 收集各自发布的 gh 使用技巧吧...

**Comment by ZoomQuiet** [comment]
## Q: 这里记录吗?
~ [anxinzhu...](https://github.com/GC4WP/GC4E15gDAMA/commit/c90c394468d29ef195621e606b47ea07f122d944#commitcomment-21530185)


## A: github 的功能和 URI/链接是一一对应的

- 提案 Issue: 
    + -> `https://github.com/[组织]/[仓库]/issues/[编号]`
    + 例如: https://github.com/GC4WP/GC4E15gDAMA/issues/1
- 仓库 Repository: 
    + -> `https://github.com/[组织]/[仓库]`
    + 例如: https://github.com/GC4WP/GC4E15gDAMA
- 仓库目录: 
    + -> `https://github.com/[组织]/[仓库]/tree/master/[目录]`
    + 例如: https://github.com/GC4WP/GC4E15gDAMA/tree/master/S10E15
- 仓库文件: 
    + -> `https://github.com/[组织]/[仓库]/tree/master/[目录]/[文件名]`
    + 例如: https://github.com/GC4WP/GC4E15gDAMA/blob/master/S10E15/S10E15_TUV.md
- 版本复审: 
    + -> `https://github.com/[组织]/[仓库]/commit/[版本UUID]`
    + 例如: https://github.com/GC4WP/GC4E15gDAMA/commit/c90c394468d29ef195621e606b47ea07f122d944
- ...

**Comment by ZoomQuiet** [comment]
~ [你真的会使用Github吗？ - 不挑食的程序员 - SegmentFault](https://segmentfault.com/a/1190000008867338)

快捷键永远是提高生命体验的选择之一...

@GC4WP/zq4s07e15

**Comment by BrookSongBrookSong** [comment]
＃成员笔记——029

1. eTimelogger2 csv导出后需要粘贴；action需要调整？
2. MIDORI MD Notebook MDb笔记本
3. Bose QC35 Bose QuietComfort 35 无线耳机
4. ASCII图谱－－大妈说他是手绘的
5. eTimelogger2 csv在ios ipad环境下导出为document，然后我发现我没有在ipad上用过document，就是说我找不到导出文件。
6. 我发现最便捷地沟通ipad和macbook的软件，依然是微信。
7. Github code界面无法插入表格和图片

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
